---
title: On Dedekind
author: Brian Zhang
date: '2025-04-20'
slug: on-dededkind
categories: []
tags: []
---

An extended quote from John Stilwell's *Elements of Algebra*, p. 35-36:

"[Gauss's] *Disquisitiones* became the bible of the next generation of number theorists, particularly Dirichlet, who kept a copy of it on his desk at all times. Dirichlet's lectures became a classic in their turn when edited by Dedekind as the book *Vorlesungen über Zahlentheorie*. The first edition appeared in 1863 (four years after Dirichlet's death) and the book gradually changed character as Dedekind added appendices in subsequent editions. The final (4th) edition contains as much Dedekind as Dirichlet....

"Dirichlet proved some of the fundamental theorems about algebraic integers, but it was Dedekind who isolated the underlying field and ring properties which explain their similarities with ordinary integers. By making the algebraic structures of number theory the object of study, Dedekind paved the way for abstract algebra. His immediate successors, Weber and Hilbert, still spoke of algebraic number theory rather than ring theory, but the next generation, led by Emmy Noether and Emil Artin, left number theory behind. The definitive account of their teaching, van der Waerden's *Moderne Algebra* [1931], was the first of the "groups, rings, and fields" books that are now standard.…

"Dedekind's reflections on the nature of integers did not end with their algebraic properties. He was also the first to recognise the fundamental role of induction in $\mathbb{N}$.... He came to the conclusion that the essence of the natural number concept is the process of closure under the successor operation, which entails the inductive property of $\mathbb{N}$. He also realised that this property makes it possible to define $+$ and $\times$, so that all of number theory really depends on induction (Dedekind [1888], Theorem 126). This radical rethinking of the nature of number was possible only with the help of the set concept ... **In fact many of Dedekind's contributions to mathematics stem from his introduction of sets as mathematical objects.** For example, it was his idea to work with congruence *classes*, as algebraic objects, rather than with the congruence *relation* on $\mathbb{Z}$ (Dedekind [1857]). He also used sets to give an elegant definition of real numbers, as we shall see in Chapter 3. [bold emphasis mine]"

Dedekind feels to me like the first "modern" mathematician, where modern refers to the style of treatment you would expect from an advanced undergraduate math class. As I‘ve studied him, he emerges as a pivotal figure, a hidden great in math history. Besides Stillwell's observations that Dedekind formalized ring theory and field theory, I have been mulling over the three constructions Stillwell is alluding to.

## Irrational numbers

In 1872, Dedekind first published on the Dedekind cuts that bear his name, in the essay *[Stetigkeit und die Irrationalzahlen](https://ia600204.us.archive.org/32/items/cu31924001586282/cu31924001586282.pdf)* (*Continuity and Irrational Numbers*). These defined each irrational number as the set of rational numbers less than it. For instance, the irrational number $\sqrt{2}$ can be identified with the set of rational numbers satisfying either $x < 0$ or $x^2 < 2$ (or both). These sets have an addition and multiplication operation: the addition / multiplication of two such sets is the set that can be obtained by adding or multiplying any two elements, one from each set.

By defining arithmetic operations on these sets, Dedekind provided a formal grounding of the concept of irrational numbers. (Alternate formulations were given by Cantor and Weierstrass at around the same time, see [here](https://en.wikipedia.org/wiki/Construction_of_the_real_numbers#Explicit_constructions_of_models).) Realizing the importance of such foundations, Dedekind wrote that his construction enables "proofs of theorems (as, e.g., $\sqrt{2} \cdot \sqrt{3} = \sqrt{6}$, which to the best of my knowledge have never been established before)" (p. 22 [here](https://ia600204.us.archive.org/32/items/cu31924001586282/cu31924001586282.pdf)). That's a fun quote, and one I'm continuing to mull over as I've been thinking about the geometric concept of number in Euclid's *Elements* (hopefully a future post).

So far, I introduced an irrational number as the set of rational numbers less than it, and showed how we could define the set for $\sqrt{2}$. This works for algebraic numbers, where we can write definitions using polynomial expressions (like $x^2 < 2$). But it leaves out irrational numbers that don't have a corresponding equation. For Dedekind, the most important part of his irrational numbers was to show that the real number line has "no gaps", hence the title *Continuity and Irrational Numbers*. We need to be able to talk about an irrational number even when there is no rule for picking out the corresponding set.

This is where Dedekind's full definition of a cut comes in. A set of rationals forms a valid irrational number if each rational in the set is less than every rational not in the set. With this extra step, we can talk about "all irrationals", and this allows us to "complete" the real line. (See also Dedekind's comments on this in his preface to the first edition of *Was sind und was sollen die Zahlen?*, for instance by searching the keyword "Bertrand" [here](http://aleph0.clarku.edu/~djoyce/numbers/dedekind.pdf).)

The following quote from *Continuity and the Irrational Numbers* has become a favorite of math historians. We see how Dedekind's cuts were invented to solve the problem of foundations of analysis:

"My attention was first directed towards the considerations which form the subject of this pamphlet in the autumn of 1858. As professor in the Polytechnic School in Zürich I found myself for the first time obliged to lecture upon the elements of the differential calculus and felt more keenly than ever before the lack of a really scientific foundation for arithmetic ... For myself this feeling of dissatisfaction was so overpowering that I made the fixed resolve to keep meditating on the question till I should find a purely arithmetic and perfectly rigorous foundation for the principles of infinitesimal analysis. ... I succeeded Nov. 24, 1858. ... I could not make up my mind to its publication, because, in the first place, the presentation did not seem altogether simple, and further, the theory itself had little promise." (p. 1-2 [here](https://ia600204.us.archive.org/32/items/cu31924001586282/cu31924001586282.pdf))

Dedekind goes on to say he was motivated to publish (in 1872) upon reading a paper by E. Heine. Heine also influenced Cantor's set theory, and Cantor's definition of real numbers came out just a few months earlier in 1872, as the introduction to *Continuity* describes. Apparently, 1872 was also the year Dedekind and Cantor first met.

## Ideals and congruence classes

Dedekind's second famous construction is defining ideals as sets of numbers. Above, Stillwell mentions the elementary case of congruence classes in modular arithmetic. When talking about arithmetic modulo say 5, we usually think of elements 0, 1, 2, 3, 4, with some redefinition of operations, such as 3 + 4 = 2. But at a higher level of abstraction, mathematicians will write this as $\mathbb{Z}/5\mathbb{Z}$, and consider 5 infinite sets: {..., -10, -5, 0, 5, 10, ...}, {..., -9, -4, 1, 6, 11, ...}, {..., -8, -3, 2, 7, 12, ...}, {..., -7, -2, 3, 8, 13, ...}, and {..., -6, -1, 4, 9, 14, ...}. The correspondence here is that each set is the elements of the integers congruent to x modulo 5. Now, instead of saying 3 + 4 = 2, we say that we add the set {..., -7, -2, 3, 8, 13, ...} with the set {..., -6, -1, 4, 9, 14, ...} by considering all pairwise sums of one element from each set. This turns out to give us another one of our sets, {..., -8, -3, 2, 7, 12, ...} — the analogous statement to 3 + 4 = 2. The nice thing about this viewpoint is not needing to worry about the "wraparound" of operations.

It seems that Dedekind was the first to talk about congruence classes in this way, in an 1857 paper called "Abriss einer Theorie der höheren Kongruenzen in bezug auf einen reellen Primzahl-Modulus" (see p. 258-264 [here](https://hal.science/tel-01144626/file/Haffner_These_1711%20-%20avec%20corrigenda.pdf) for a summary). I agree with Emmylou Haffner that this early project "might have been an inspiration for Dedekind's later works" on ideals (p. 259), and indeed might have influenced his 1858 cuts.

So what is an ideal? Rather than a definition, I'll give the most basic example. When I above wrote $\mathbb{Z}/5\mathbb{Z}$, $\mathbb{Z}$ refers to the integers (positive, negative, and zero), $5\mathbb{Z}$ refers to the particular infinite set containing 0 ({…, -10, -5, 0, 5, 10, …}), and $/$ is called the quotient operation, which divides up $\mathbb{Z}$ into the 5 classes based on $5\mathbb{Z}$. Now, $5\mathbb{Z}$ is an example of an ideal. In fact, the ideals in $\mathbb{Z}$ are simply $n\mathbb{Z}$ (the set of multiples of $n$) for every positive integer $n$. This includes $1\mathbb{Z}$ which is just $\mathbb{Z}$.

Now for a cool thing you can do with these ideals. It turns out that the integer $m$ divides the integer $n$ if and only if the ideal $m\mathbb{Z}$ contains the ideal $n\mathbb{Z}$. So for example, we know that 2 divides 6 — this translates into $2\mathbb{Z}$ containing $6\mathbb{Z}$, as we can see that {.., -8, -6, -4, -2, 0, 2, 4, 6, 8, …} contains the subset {.., -6, 0, 6, …}. Note that while 6 is bigger than 2, $2\mathbb{Z}$ is "bigger than" $6\mathbb{Z}$. As another example, 1 divides every $n$, and we have that $1\mathbb{Z}$ contains every ideal $n\mathbb{Z}$. We can begin to talk about divisibility of integers simply by talking about containment of the respective ideals. This is often summarized by saying that for ideals, "to contain is to divide".

Dedekind's formalization of the concept of ideals took the work of Kummer (see [here](https://en.wikipedia.org/wiki/Ideal_number#History)) and put it on a solid foundation. I haven't yet studied the original works, though [this essay](https://digitalcommons.ursinus.edu/cgi/viewcontent.cgi?article=1000&context=triumphs_abstract) by Janet Heine Barnett seems like a great place to start. All in all, Dedekind put out 4 editions of Dirichlet's *Lectures on Number Theory* (1863, 1871, 1879, 1894); the first appearance of his theory of ideals was in the second edition of 1871, in Supplement X. Other sources of Dedekind's ideal theory are in the third and fourth editions, as well as an 1877 manuscript originally published in French (thanks to [this reference](https://www.andrew.cmu.edu/user/avigad/Papers/ideals71.pdf) by Jeremy Avigad for helping me clear up the timeline). As Stillwell notes, this work was taken up and developed by Weber, Hilbert, Noether, Artin, and van der Waerden, with Noether famously telling her students, "Everything is already in Dedekind".

## Natural numbers

Dedekind's third revolutionary construction is of the natural numbers, essentially what we now call the Peano axioms. This was published in 1888 as *What are Numbers and What are They For?* In the preface to the first edition, Dedekind reflects upon his project for a general audience:

"My answer to the problems propounded in the title of this paper is, then, briefly this: numbers are free creations of the human mind; they serve as a means of apprehending more easily and more sharply the difference of things. It is only through the purely logical process of building up the science of numbers and by thus acquiring the continuous number-domain that we are prepared accurately to investigate our notions of space and time by bringing them into relation with this number-domain created in our mind. If we scrutinise closely what is done in counting an aggregate or number of things, we are led to consider the ability of the mind to relate things to things, to let a thing correspond to a thing, or to represent a thing by a thing, an ability without which no thinking is possible. Upon this unique and therefore absolutely indispensable foundation, as I have already affirmed in an announcement of this paper, must, in my judgment, the whole science of numbers be established." (p. 31 [here](http://aleph0.clarku.edu/~djoyce/numbers/dedekind.pdf), or p. 31-32 [here](https://ia600204.us.archive.org/32/items/cu31924001586282/cu31924001586282.pdf))

In other parts of this preface, Dedekind ties his goals into that of *Continuity and Irrational Numbers*. It was the success of that project — reducing the real numbers down to the rationals, and hence the integers — that pushed Dedekind to reflect further on the foundations of integer arithmetic. Dedekind landed on the importance of mappings between objects, for mapping / correspondence is what we do when we count, and this provided the starting point for his exploration. The entire essay is a slow build of logical inferences upon each other, leading to definitions of addition, multiplication, exponentiation, and the cardinality of a finite set.

I found the climax of the work to be when Dedekind first introduces the natural numbers:

“73. Definition. If in the consideration of a simply infinite system $N$ set in order by a transformation $\phi$ we entirely neglect the special character of the elements; simply retaining their distinguishability and taking into account only the relations to one another in which they are placed by the order-setting transformation $\phi$, then are these elements called *natural numbers* or *ordinal numbers* or simply *numbers*, and the base-element 1 is called the *base-number* of the *number-series* $N$. With reference to this freeing the elements from every other content (abstraction) we are justified in calling numbers a free creation of the human mind. The relations or laws which are derived entirely from the conditions $\alpha$, $\beta$, $\gamma$, $\delta$ in (71) and therefore are always the same in all ordered simply infinite systems, whatever names may happen to be given to the individual elements (compare 134), form the first object of the *science of numbers* or *arithmetic*.”

I borrowed a copy of *Numbers* from my university library, and found the rest of the essay dryer than I was expecting (but Dedekind is unashamed of his style, see his first preface). If you haven't seen the construction of the natural numbers before, it may be better to read a modern treatment of Peano's axioms, for instance p. 6-7 of [this writeup](https://dongryul-kim.github.io/harvard_notes/Math55a/Notes_Math55a.pdf).

For those who would like to give Dedekind a try, [here](http://aleph0.clarku.edu/~djoyce/numbers/dedekind.pdf) is a reading guide. The translation I skimmed also pointed out Dedekind's gaps in proof when he claimed things we now know to be not unique, due to models such as (1) non-standard models of arithmetic (a gap in Dedekind's 73 and 134) and (2) infinite but not Dedekind-infinite sets (a gap in Dedekind's 159 and 160) — this could be of interest to someone studying history of logic.

The editors / translations of my volume, H. Pogorzelski, W. Ryan and W. Snyder, also wrote a nice introduction which I paid close attention to (sadly, they took out Dedekind's prefaces!):

"The unique creativity of Dedekind blazes across this essay on arithmetic like lightning across a serene sky. Indeed, it is a highly educational experience for college students to see and learn from this mathematical giant as he stumbles, forgets, worries, slips, trips, sweats and unearths his precious mathematical mines single-handed lay before our eyes in his essay. Dedekind's essay unearths the following branches of mathematics:

1. *Axiomatic Set Theory*, hinting implicitly at most of the Zermelo axioms, which surely led Zermelo to his formalization of them.
2. *Axiomatic Arithmetic*, hinting at the Peano axioms, which Peano must have noted.
3. *Recursive Function Theory*, hinting at Computability, which Skolem, Gödel and Kleene must have noted for their work.
4. *Foundations of Mathematics*, which surely guided Zermelo and Bertrand Russell in their seminal foundational enterprises. It should be noted that the true founder of set-theoretic foundations of mathematics is Dedekind and not Cantor as many imagine."

Stillwell observes, "The effective use of the set concept in mathematics probably begins with Dedekind's definition of real numbers in 1858" (p. 53). Dedekind, driven by abstraction and parsimony, discovered the utility of constructing sets of numbers and applied it multiple times in his career. In developing the implications of this set-centered viewpoint, he resolved major questions of foundations, while in a way his and others' success led to troubled examination of the set concept that came to dominate mathematics at the turn of the 20th century.

## Further Reading

- [*Essays on the Theory of Numbers*](https://ia600204.us.archive.org/32/items/cu31924001586282/cu31924001586282.pdf), 1901 English translation by W. Beman containing Dedekind's *Continuity and Irrational Numbers* (1872) and *What are Numbers and What are They For?* (1888)
- "[Richard Dedekind and the Creation of an Ideal: Early Developments in Ring Theory](https://digitalcommons.ursinus.edu/cgi/viewcontent.cgi?article=1000&context=triumphs_abstract)", Janet Heine Barnett, 2016
- Peano's Axioms and Dedekind Cuts, p. 5-13 of [Math 55a course notes](https://dongryul-kim.github.io/harvard_notes/Math55a/Notes_Math55a.pdf#page9), lectures by Yum-Tong Siu, notes by Dongryul Kim, 2015
- "[Notes on Richard Dedekind's *Was sind und was sollen die Zahlen?*](http://aleph0.clarku.edu/~djoyce/numbers/dedekind.pdf)", David E. Joyce, 2005
- [*The "Science of Numbers" in action in Richard Dedekind's works: between mathematical explorations and foundational investigations*](https://hal.science/tel-01144626/file/Haffner_These_1711%20-%20avec%20corrigenda.pdf), Emmylou Haffner, 2015

***Update 2025-05-08: Added recommended reading list. Rewrote all 3 subsections. Added the clarification on irrational numbers that do not have a formula for defining them. Added the example of divisibility of ideals in the integers. Added excerpts from Dedekind's "Numbers".***
